version: "3"
services:
  webserver:
    build:
      context: webserver
      dockerfile: WebServer.dockerfile
    tty: true
    volumes:
      - ./webserver/:/webserver/
    networks:
      dmz:
        ipv4_address: 172.26.0.2
    ports:
      - "443:443"
  caserver:
    build:
      context: caserver
      dockerfile: CAServer.dockerfile
    tty: true
    volumes:
      - ./caserver/:/caserver/
    ports:
      - "8043:443"
    networks:
      internal_net:
        ipv4_address: 172.27.0.2
  firewall:
    build:
      context: firewall
      dockerfile: FireWall.dockerfile
    tty: true
    privileged: true
    networks:
      internal_net:
        ipv4_address: 172.27.0.254
      dmz:
        ipv4_address: 172.26.0.254
  database:
    build:
      context: database
      dockerfile: Database.dockerfile
    networks:
      internal_net:
        ipv4_address: 172.27.0.3
    ports:
      - "3306:3306"

#  backupserver:
#    build:
#      context: backupserver
#      dockerfile: BackupServer.dockerfile
#    tty: true
#    networks:
#      internal_net:
#        ipv4_address: 172.27.0.4
#    ports:
#      - "22:22"
  backupserver:
    image: atmoz/sftp
    ports:
        - "2222:22"
    command: sftp_manager:sup3r_s3cr3t_sftp:1001

networks:
  internal_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.27.0.0/16
  dmz:
    driver: bridge
    ipam:
      config:
        - subnet: 172.26.0.0/16
