version: "3"
services:
  webserver:
    build:
      context: webserver
      dockerfile: WebServer.dockerfile
    tty: true
    volumes:
      - ./webserver/:/webserver/
    networks:
      dmz:
        ipv4_address: 172.16.0.2
    ports:
      - "443:443"
  caserver:
    build:
      context: caserver
      dockerfile: CAServer.dockerfile
    tty: true
    volumes:
      - ./caserver/:/caserver/
    networks:
      internal_net:
        ipv4_address: 172.17.0.2
  firewall:
    build:
      context: firewall
      dockerfile: FireWall.dockerfile
    tty: true
    privileged: true
    networks:
      internal_net:
        ipv4_address: 172.17.0.254
      dmz:
        ipv4_address: 172.16.0.254
  database:
    build:
      context: database
      dockerfile: Database.dockerfile
    networks:
      internal_net:
          ipv4_address: 172.17.0.3
    ports:
      - "3306:3306"

  backupserver:
    build:
      context: backupserver
      dockerfile: BackupServer.dockerfile
    tty: true
    networks:
      internal_net:
          ipv4_address: 172.17.0.4

networks:
  internal_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.17.0.0/16
  dmz:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/16
